<?php

return [
    [
        'img' => 'https://www.boolean.careers/images/people/ortenzi.png',
        'nome' => 'DANIELA ORTENZI',
        'anni' => 27,
        'genere' => 'f',
        'slug' => 'daniela-ortenzi',
        'azienda' => 'RDS Radio Dimensione Suono',
        'descrizione' => 'Laureata in psicologia alla Sapienza di Roma con una nascente carriere nella SEO, Daniela si iscrive al corso Boolean. Ora lavora come web developer presso RDS Radio Dimensione Suono.',
    ],
    [
        'img' => 'https://www.boolean.careers/images/people/antidormi.png',
        'nome' => 'NICHOLAS ANTIDORMI',
        'anni' => 20,
        'genere' => 'm',
        'slug' => 'nicholas-antidormi',
        'azienda' => 'Atoms Studio',
        'descrizione' => 'Intraprende gli studi universitari in matematica per le sue doti analitiche, ma abbandona il percorso per concentrarsi su uno più pratico e orientato alla richiesta del mercato del lavoro: la programmazione',
    ],
    [
        'img' => 'https://www.boolean.careers/images/people/biagini.png',
        'nome' => 'ALESSANDRO BIAGINI',
        'anni' => 26,
        'genere' => 'm',
        'slug' => 'alessandro-biagini',
        'azienda' => 'DISC SPA',
        'descrizione' => 'Da giocatore professionista di basket a sviluppatore web. 6 mesi di impegno da MVP e un memorabile tap-in targato Boolean hanno garantito ad Alessandro un solido futuro come web developer.',
    ],
    [
        'img' => 'https://www.boolean.careers/images/people/davide.png',
        'nome' => 'DAVIDE PATRUNO',
        'anni' => 29,
        'genere' => 'm',
        'slug' => 'davide-patruno',
        'azienda' => 'ArmadioVerde',
        'descrizione' => 'Dopo la laurea magistrale in scienze umanistiche e sociali, si concentra sullo sviluppo di strategie marketing. Decide di cambiare vita, questa volta puntando sullo sviluppo Front-End.',
    ],
    [
        'img' => 'https://www.boolean.careers/images/people/quarticelli.png',
        'nome' => 'SIMONE QUARTICELLI',
        'anni' => 32,
        'genere' => 'm',
        'slug' => 'simone-quarticelli',
        'azienda' => 'VLC 2',
        'descrizione' => 'Per supportare la famiglia, Simone inizia a lavorare come operaio da giovanissimo. Fortemente motivato a cambiare vita, per 6 mesi non stacca mai lo sguardo dal traguardo, distinguendosi per tenacia e resilienza.',
    ],
    [
        'img' => 'https://www.boolean.careers/images/people/rispoli.jpeg',
        'nome' => 'MARCO RISPOLI',
        'anni' => 28,
        'genere' => 'm',
        'slug' => 'marco-rispoli',
        'azienda' => 'MyCibus srl',
        'descrizione' => 'Dopo una prima esperienza come Social Media Manager e Web Developer su piattaforma Wordpress, Marco decide di iscriversi a Boolean spinto dalla sua ricerca di perfezione e dalla sua caparbietà.',
    ],
    [
        'img' => 'https://www.boolean.careers/images/people/giannone.jpeg',
        'nome' => 'VALENTINA GIANNONE',
        'anni' => 38,
        'genere' => 'f',
        'slug' => 'valentina-giannone',
        'azienda' => 'Bloovery',
        'descrizione' => 'Un passato come responsabile di laboratorio odontotecnico, per poi decidere che non era la sua vera vocazione. Valentina ha deciso di prendere il coraggio a due mani e lanciarsi con successo nel mondo del web development.',
    ],
    [
        'img' => 'https://www.boolean.careers/images/people/fontana.jpeg',
        'nome' => 'LUIGI FONTANA',
        'anni' => 27,
        'genere' => 'm',
        'slug' => 'luigi-fontata',
        'azienda' => 'MG Group Italia',
        'descrizione' => 'Luigi è un amante della matematica e ha partecipato alle Finali Italiane delle Olimpiadi di Matematica. La programmazione è un modo per potare i numeri verso l’altra sua grande passione: il computer.',
    ],
];